global NUM_ELEM NUM_NODE NUM_LOADS NUM_SPC;
global NUM_PHYS_PROP NUM_MATERIAL;
global NUM_CS N_EQ N_UNKNOWN NUM_RBAR;
global ID ENODE ELEM_TYPE;
global LOADED_NODES DCS CS_ID; 
global P_ID M_ID PHYS_PROP_ID MAT_ID;
global SPC_NODE SPC_DIR RBAR_ID;
 
global X Y U V THETA_Z;
global F_X F_Y;
global AREA MOM_INERTIA H1 H2;
global KSHEAR THICK;
global E_MODULUS G_MODULUS RHO ALPHA 
global TREF PRATIO;
global GX GY TEMPD T_CS CONSTR_DISP;
global S SE R RE DISP;
global STRESS ELEM_FORCE;
global REACT_FORCE;

global TITLE;

global TEMP_INPUT ERROR_F OUTFID INFID;
global USE_QM6;     USE_QM6 = true;

